name: Dump
description: |
  環境変数と github context をログへ出力します。
  ワークフローのデバッグに便利です。
inputs:
  enable-context:
    type: boolean
    default: true
    required: false
    description: github context をログに出力するか
outputs:
  dumped-date:
    value: ${{ steps.current.outputs.date }}
    description: ダンプ日時
runs:
  using: composite
  steps:
    - shell: bash
      run: printenv | sort
    - if: ${{ inputs.enable-context }}
      shell: bash
      env:
        CONTEXT: ${{ toJSON(github) }}
      run: echo "${CONTEXT}"
    - id: current
      shell: bash
      run: echo "date=$(date)" >> "${GITHUB_OUTPUT}"
